### ISSUE TITLE
GA Release Compatible With Grails 6.2.1+

### ISSUE THREAD

**Issue by jeffscottbrown** [codeconsole/grails-sitemesh3#2]
Is it known when a GA release will be available that is compatible with Grails 6.2.1?

Thank you!

**Comment by codeconsole** [comment]
Have you tried using the 6.2.0 release? Unfortunately, it requires adding a gradle configuration excluding the grails-sitemesh2-plugin and sitemesh 2 dependencies.

I would favor using Sitemesh 2 with Grails 6.2.x, but grails-boot currently uses the 6.2.0 release for its examples with 6.2.x

**Comment by jeffscottbrown** [comment]
> Have you tried using the 6.2.0 release? 

No, but if it isn't compatible with that, that isn't an issue for my need.

> I would favor using Sitemesh 2 with Grails 6.2.x

Understood.

My question was to ask if you know when a GA version that was compatible with 6.2.1+ might be available.  I saw your note in Slack about this being usable in Grails 6 and 7, and that is what I am trying to configure.  I understand you favor Sitmesh 2.

Thank you for your input!

**Comment by codeconsole** [comment]
I am referring to the 6.2.0 version of the plugin.  The 6.2.0 version is compatible with 6.2.1 of Grails.  And as I mentioned, it also works with 6.2.2-SNAPSHOT which can be seen by running the 6.2.x branch of grails-boot

**Comment by jeffscottbrown** [comment]
> I am referring to the 6.2.0 version of the plugin. 

Thank you!  I thought you meant Grails 6.2.0.  That is perfect. 

> And as I mentioned, it also works with 6.2.2-SNAPSHOT 

I missed that mention.  I am going to go with 6.2.0 and am all set.  Thank you again!
